;;++++++++++++++++++++++++++++++++++++++++++++++++++
;; Generating graphs about clusters
;;++++++++++++++++++++++++++++++++++++++++++++++++++

;;--------------------------------------------------
;; Cluster graph definitions
;;--------------------------------------------------

(defvar clustercounter 0)

(defun nth-of (n tbl)
  (car (nth (1- n) tbl)))

(defun clusterofone-node (elem tbl counter)
  (format "subgraph cluster%s {\n%s\n}\n"
          counter (clusterofone elem (1+ counter) tbl)))

(defun clusterofone-leaf (elem tbl next)
  (let ((first  (nth-of elem tbl))
        (second (library-belong (1- elem))))
    (if (listp next)
        (format "%s [URL=\"./%s.html\"];\n"
                first second)
        (format "%s [URL=\"./%s.html#%s\"]; %s -> %s[style=invis]\n"
                first second first first (nth-of next tbl)))))

(defun clusterofone (lst counter tbl)
  (do ((temp lst (cdr temp))
       (res ""))
      ((endp temp) res)
    (let ((elem (car temp)))
      (concat-to res (if (listp elem)
                         (clusterofone-node elem tbl counter)
                         (clusterofone-leaf elem tbl
                                            (when (cdr temp) (cadr temp))))))))

(defun clusterofseveral (lol)
  (clusterofseveral-aux (clusterofone lol 1 tables-definitions)))

(defun show-diagram-clusters (text)
  (with-temp-file "temp.gv"
    (insert text))
  (shell-command "dot -Tcmap temp.gv -o temp.map")
  (shell-command "dot -Tpng temp.gv -o temp.png")
  (createwebpage)
  (shell-command "xdg-open temp.html"))

(defun showclustergraph (lol)
  (show-diagram-clusters (clusterofseveral lol)))

(defun createwebpage ()
  (with-temp-file "temp.html"
    (insert (createwebpage-aux (read-lines "temp.map")))))

(defun issubcluster (cluster1 cluster2)
  (do ((temp cluster1 (cdr temp))
       (res nil))
      ((or (endp temp)
           res)
       (not res))
    (if (not (member (car temp)
                     cluster2))
        (setf res t))))

(defun replacecluster (cluster1 cluster2)
  (if (endp cluster2)
      (list cluster1)
    (if (listp (car cluster2))
        (if (issubcluster cluster1 (car cluster2))
            (cons (replacecluster cluster1 (car cluster2))
                  (cdr cluster2))
          (cons (car cluster2)
                (replacecluster cluster1 (cdr cluster2))))
      (if (member (car cluster2)
                  cluster1)
          (replacecluster cluster1 (cdr cluster2))
        (cons (car cluster2)
              (replacecluster cluster1 (cdr cluster2)))))))

(defun subclusters (cluster clusters)
  (do ((temp clusters (cdr temp))
       (flag nil)
       (flag1 nil)
       (res nil))
      ((or (endp temp)
           flag flag1)
       (cond (flag (append (reverse res)
                           temp))
             (flag1 clusters)
             (t (append (reverse res)
                        (list cluster)))))
    (cond ((not (issubcluster cluster (car temp)))
           (setf res (cons (car temp)
                           res)))
          ((equal cluster (car temp))
           (setf res (reverse clusters))
           (setf flag1 t))

          (t
           (setf res (cons (replacecluster cluster (car temp))
                           res))
           (setf flag t)))))

(defun subclustersseveral (clusters1 clusters2)
  (do ((temp clusters1 (cdr temp))
       (temp2 clusters2))
      ((endp temp)
       temp2)
    (setf temp2 (subclusters (car temp)
                             temp2))))

(defun dependencygraph-defs ()
  (interactive)
  (let ((clusters1 nil)
        (clusters3 nil))
    (setf granularity-level 3)
    (weka-defs)
    (sleep-for 2)
    (setf clusters1 (cdr (form-clusters (extract-clusters-from-file-defs )
                                        (floor (length tables-definitions)
                                               5))))
    (setf granularity-level 5)
    (weka-defs)
    (sleep-for 2)
    (setf clusters3 (cdr (form-clusters (extract-clusters-from-file-defs )
                                        (floor (length tables-definitions)
                                               2))))
    (showclustergraph (subclustersseveral  clusters3 clusters1 ))))

;;--------------------------------------------------
;; Cluster graph lemma statements
;;--------------------------------------------------

(defun clusterofone-statements (lst)
  (do ((temp lst (cdr temp))
       (res ""))
      ((endp temp)
       res)
    (if (listp (car temp))
        (progn (setf clustercounter (1+ clustercounter))
               (setf res (concat res (format "subgraph cluster%s {\n" clustercounter)
                                 (clusterofone-statements (car temp))
                                 "\n}\n")))
      (if (and (cdr temp)
               (not (listp (cadr temp))))
          (setf res (concat res
                            (format "%s [URL=\"./%s.html#%s\"]; %s -> %s[style=invis]\n" (car (nth (1- (car temp))
                                                                                                   tables-thms))
                                    (library-belong-thm (1- (car temp)))
                                    (car (nth (1- (car temp))
                                              tables-thms))
                                    (car (nth (1- (car temp))
                                              tables-thms))
                                    (car (nth (1- (cadr temp))
                                              tables-thms))
                                    )))
        (setf res (concat res
                          (format "%s [URL=\"./%s.html\"];\n" (car (nth (1- (car temp))
                                                                        tables-thms))
                                  (library-belong-thm (1- (car temp))))))))))

(defun clusterofseveral-statements (lol)
  (setf clustercounter 0)
  (concat "digraph {\n rankdir=LR;\n" (clusterofone-statements lol)
          "\n}"))

(defun showclustergraph-statements (lol)
  (show-diagram-clusters (clusterofseveral-statements lol)))

(defun dependencygraph-statements ()
  (interactive)
  (let ((clusters1 nil)
        (clusters3 nil))
    (setf granularity-level 3)
    (weka-thms)
    (sleep-for 2)
    (setf clusters1 (cdr (form-clusters (extract-clusters-from-file-defs )
                                        (floor (length tables-thms)
                                               5))))
    (setf granularity-level 5)
    (weka-thms)
    (sleep-for 2)
    (setf clusters3 (cdr (form-clusters (extract-clusters-from-file-defs )
                                        (floor (length tables-thms)
                                               2))))
    (showclustergraph-statements (subclustersseveral  clusters3 clusters1 ))))

;;--------------------------------------------------
;; Cluster graph proofs
;;--------------------------------------------------

(defun clusterofone-proof (lst)
  (do ((temp lst (cdr temp))
       (res ""))
      ((endp temp)
       res)
    (if (listp (car temp))
        (progn (setf clustercounter (1+ clustercounter))
               (setf res (concat res (format "subgraph cluster%s {\n" clustercounter)
                                 (clusterofone-proof (car temp))
                                 "\n}\n")))
      (if (and (cdr temp)
               (not (listp (cadr temp))))
          (let ((thm nil)
                (thm2 nil))
            (if (<= (car temp)
                    (length saved-theorems))
                (setf thm (car (nth (1- (car temp))
                                    saved-theorems)))
              (progn (shell-command (concat "cat "(expand-file-name "names_temp.txt")
                                            " | sed -n '"
                                            (format "%s" (- (car temp)
                                                            (length saved-theorems)))
                                            "p'"))
                     (with-current-buffer "*Shell Command Output*"
                       (beginning-of-buffer)
                       (read (current-buffer))
                       (setf thm (format "%s"  (read (current-buffer)))))))
            (if (<= (car temp)
                    (length saved-theorems))
                (setf thm2 (car (nth (1- (cadr temp))
                                     saved-theorems)))
              (progn (shell-command (concat "cat "(expand-file-name "names_temp.txt")
                                            " | sed -n '"
                                            (format "%s" (- (cadr temp)
                                                            (length saved-theorems)))
                                            "p'"))
                     (with-current-buffer "*Shell Command Output*"
                       (beginning-of-buffer)
                       (read (current-buffer))
                       (setf thm2 (format "%s"  (read (current-buffer)))))))
            (setf res (concat res
                              (format "%s; %s -> %s[style=invis]\n"
                                      thm
                                      thm
                                      thm2))))
        (let ((thm nil))
          (if (<= (car temp)
                  (length saved-theorems))
              (setf thm (car (nth (1- (car temp))
                                  saved-theorems)))
            (progn (shell-command (concat "cat "(expand-file-name "names_temp.txt")
                                          " | sed -n '"
                                          (format "%s" (- (car temp)
                                                          (length saved-theorems)))
                                          "p'"))
                   (with-current-buffer "*Shell Command Output*"
                     (beginning-of-buffer)
                     (read (current-buffer))
                     (setf thm (format "%s"  (read (current-buffer)))))))
          (setf res (concat res (format "%s;\n" thm))))))))

(defun clusterofseveral-proof (lol)
  (setf clustercounter 0)
  (concat "digraph {\n rankdir=LR;\n" (clusterofone-proof lol)
          "\n}"))

(defun showclustergraph-proof (lol)
  (show-diagram-clusters (clusterofseveral-proof lol)))

(defun dependencygraph-proof ()
  (interactive)
  (if libs-menus
      (progn (with-temp-file (expand-file-name "temp.csv")
               (cond ((string= level "g")
                      (insert (extract-features-1)))
                     ((string= level "t")
                      (insert (extract-features-2 tactic-level)))
                     ((string= level "p")
                      (insert (extract-features-2 proof-tree-level)))))
             (add-libraries-temp)
             (add-names))
    (with-temp-file (expand-file-name "temp.csv")
      (insert (extract-features-1))))
  (let ((clusters1 nil)
        (clusters3 nil))
    (setf granularity-level 3)
    (weka (floor (size-temp)
                 5))
    (sleep-for 2)
    (setf clusters1 (cdr (form-clusters (extract-clusters-from-file (floor (size-temp)
                                                                           5))
                                        (floor (size-temp)
                                               5))))
    (setf granularity-level 5)
    (weka (floor (size-temp)
                 2))
    (sleep-for 2)
    (setf clusters3 (cdr (form-clusters (extract-clusters-from-file (floor (size-temp)
                                                                           2))
                                        (floor (size-temp)
                                               2))))
    (showclustergraph-proof (subclustersseveral (removenil (remove-if-empty clusters3))
                                                (removenil (remove-if-empty clusters1))))))

(defun remove-if-empty-aux (lol thms)
  (let (result1)
    (dolist (elem1 lol result1)
      (let (result2)
        (dolist (elem2 elem1 (setf result1 (cons result2 result1)))
          (unless (string= "" (car (nth (1- elem2) thms)))
            (setf result2 (cons elem2 result2))))))))

(defun remove-if-empty (lol)
  (remove-if-empty lol saved-theorems))
