(defun switch-to-display ()
  (if noninteractive (set-buffer (get-buffer-create "*display*"))
                     (switch-to-buffer-other-window "*display*")))

(defun cluster-definitions ()
  (interactive)
  (switch-to-display)
  (weka-defs)
  (sleep-for 2)
  (print-clusters-weka-defs (cond  ((eq 2 granularity-level)
                                    (floor (length tables-definitions) 7))
                                   ((eq 3 granularity-level)
                                    (floor (length tables-definitions) 5))
                                   ((eq 4 granularity-level)
                                    (floor (length tables-definitions) 4))
                                   ((eq 5 granularity-level)
                                    (floor (length tables-definitions) 2))
                                   (t (floor (length tables-definitions) 8)))))
